/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import helpers.Conexion;
import helpers.Hash;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Usuario;
import modelo.UsuarioDAO;
/**
 *
 * @author two_r
 */
public class frmIngreso extends javax.swing.JFrame {

     int intentos = 1;
    
    /**
     * Creates new form frmIngreso
     */
    public frmIngreso() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicial = new javax.swing.JPanel();
        lblMiMasc = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtNombreUsuario = new javax.swing.JTextField();
        lblNombreUsuario = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        cboxTipoUsuario = new javax.swing.JComboBox<>();
        txtPassword = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        lblMiMascVet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesión - Flash Repair");
        setResizable(false);

        panelInicial.setBackground(new java.awt.Color(255, 255, 255));
        panelInicial.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inicio de sesión", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 15))); // NOI18N

        txtNombreUsuario.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtNombreUsuario.setToolTipText("");
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });

        lblNombreUsuario.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        lblNombreUsuario.setText("Usuario:");
        lblNombreUsuario.setToolTipText("");

        lblPassword.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        lblPassword.setText("Contraseña:");

        lblTipoUsuario.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        lblTipoUsuario.setText("Tipo de Usuario:");

        cboxTipoUsuario.setBackground(new java.awt.Color(35, 47, 62));
        cboxTipoUsuario.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cboxTipoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        cboxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GobiernoCentral", "Institucion", "Ciudadano", "Reportes" }));
        cboxTipoUsuario.setToolTipText("Seleccione uno");

        txtPassword.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtPassword.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNombreUsuario)
            .addComponent(txtPassword)
            .addComponent(cboxTipoUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombreUsuario)
                        .addContainerGap(117, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblTipoUsuario))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTipoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIniciarSesion.setBackground(new java.awt.Color(35, 47, 62));
        btnIniciarSesion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar sesión");
        btnIniciarSesion.setToolTipText("Inicio de sesión con los datos correctos");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInicialLayout = new javax.swing.GroupLayout(panelInicial);
        panelInicial.setLayout(panelInicialLayout);
        panelInicialLayout.setHorizontalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(lblMiMascVet, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblMiMasc))
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnIniciarSesion))
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelInicialLayout.setVerticalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMiMasc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMiMascVet)
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIniciarSesion)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        Conexion con = new Conexion(); 
 //       Usuario mod = new Usuario();
        
        try{
            con.connectar();
            ResultSet rs = con.seleccionar("SELECT * FROM usuarios WHERE usuario LIKE '" + txtNombreUsuario.getText()
                + "' AND contrasena LIKE '" + txtPassword.getText()+ "'");

            if (intentos <4 && rs.next()) {//Si hay registros?
                this.dispose();
                frmVentanaPrincipal ventp = new frmVentanaPrincipal();
                ventp.setVisible(true);
                

            } else if (intentos!=4){
                JOptionPane.showMessageDialog(rootPane, "Usuario y/o clave invalida",
                    "Usuario", JOptionPane.ERROR_MESSAGE);
            }
            else
            { JOptionPane.showMessageDialog(rootPane,"Mas de 3 intentos fallidos", "Ingreso", JOptionPane.ERROR_MESSAGE);
                txtNombreUsuario.setEditable(false);
                txtPassword.setEditable(false);
            }
            intentos++;

        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        /*
        UsuarioDAO dao = new UsuarioDAO();
        Usuario u = new Usuario();

        if(!txtNombreUsuario.getText().equals("") && !txtPassword.getText().equals("")){
            u.setUsuario(txtNombreUsuario.getText());
            u.setContrasena(txtPassword.getText());
            u.setTipoRol((Integer) cboxTipoUsuario.getSelectedItem());

            if(dao.login(u)){
                this.dispose();
                //dispose para ocultar
                String idUsuario = String.valueOf(dao.cargarIdUsuario(txtNombreUsuario.getText()));

                String nomUsuario = txtNombreUsuario.getText();
                String tipoUsuario = cboxTipoUsuario.getSelectedItem().toString();
                frmVentanaPrincipal frm = new frmVentanaPrincipal(idUsuario, nomUsuario, tipoUsuario);
                frm.setVisible(true); // que sea visible
            }
            else{
                JOptionPane.showMessageDialog(null,"Datos Incorrectos");

            }

        }else{
            JOptionPane.showMessageDialog(null,"Debe Ingresar sus datos");
        }
        */
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIniciarSesion;
    public javax.swing.JComboBox<String> cboxTipoUsuario;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblMiMasc;
    public javax.swing.JLabel lblMiMascVet;
    public javax.swing.JLabel lblNombreUsuario;
    public javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTipoUsuario;
    public javax.swing.JPanel panelInicial;
    public javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
