/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControllerReporteyListadoAverias;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelo.ReporteyListadoAveriasDAO;

/**
 *
 * @author Susana Burch
 */
public class frmReporteyListadoAverias extends javax.swing.JFrame{
    
    String columnas[] = {"numeroAveria", "usuario", "nivelIncidencia", "fechaAveria", "provincia", "canton", "distrito", "direccionExacta", "descripcionAveria", "imagen", "institucionReportar", "estadoAveria"};
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
    ReporteyListadoAveriasDAO dao = new ReporteyListadoAveriasDAO();
    ArrayList<Object[]> registros = new ArrayList<>();

    private JFrame frame;
    /**
     * Creates new form frmReporteyListadoAverias
     */
    public frmReporteyListadoAverias() {
        initComponents();
        cargarTabla();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
   
    public frmReporteyListadoAverias(JFrame frame) {
        initComponents();
        this.frame = frame;
        cargarTabla();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
     private void cargarTabla (){
         
        this.registros = dao.listar();
        modelo.setNumRows(0);
        for  (Object [] record : registros){
            this.modelo.addRow(record);
        }
        this.tableAverias.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMant = new javax.swing.JPanel();
        lblTitleAverias = new javax.swing.JLabel();
        panelDetalleAverias = new javax.swing.JPanel();
        lblBuscarAveria = new javax.swing.JLabel();
        btnBuscarAveria = new javax.swing.JButton();
        txtBuscarAveria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAverias = new javax.swing.JTable();
        btnEliminarAverias = new javax.swing.JButton();
        btnRefrescarAveria = new javax.swing.JButton();
        panelIngresarDatosMasc = new javax.swing.JPanel();
        lblIdMasc = new javax.swing.JLabel();
        lblNombreMasc = new javax.swing.JLabel();
        lblNivelIncidencia = new javax.swing.JLabel();
        txtNumeroAveria = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        lblProvincia = new javax.swing.JLabel();
        lblCanton = new javax.swing.JLabel();
        btnCancelarAverias = new javax.swing.JButton();
        btnGuardarAverias = new javax.swing.JButton();
        btnEditarAverias = new javax.swing.JButton();
        cboxNivelIncidencia = new javax.swing.JComboBox<>();
        cboxProvincia = new javax.swing.JComboBox<>();
        lblActivoMasc = new javax.swing.JLabel();
        cboxEstadoAveria = new javax.swing.JComboBox<>();
        lblDistrito = new javax.swing.JLabel();
        txtInstitucion = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblImagen = new javax.swing.JLabel();
        btnBuscarImagen = new javax.swing.JButton();
        lblInstitucion = new javax.swing.JLabel();
        txtDistrito = new javax.swing.JTextField();
        txtCanton = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        JLImg = new javax.swing.JLabel();
        lblLogoMasc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMant.setBackground(new java.awt.Color(255, 255, 255));
        panelMant.setForeground(new java.awt.Color(255, 255, 255));

        lblTitleAverias.setFont(new java.awt.Font("SansSerif", 3, 22)); // NOI18N
        lblTitleAverias.setText("MANTENIMIENTO DE REPORTE Y LISTADO DE AVERÍAS");

        panelDetalleAverias.setBackground(new java.awt.Color(255, 255, 255));
        panelDetalleAverias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        lblBuscarAveria.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblBuscarAveria.setText("Buscar por número de avería:");

        btnBuscarAveria.setBackground(new java.awt.Color(255, 153, 0));
        btnBuscarAveria.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnBuscarAveria.setText("BUSCAR");
        btnBuscarAveria.setToolTipText("Busca por nombre la mascota");

        txtBuscarAveria.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        tableAverias.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tableAverias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "numeroAveria", "usuario", "nivelIncidencia", "fechaAveria", "provincia", "canton", "distrito", "direccionExacta", "descripcionAveria", "imagen", "institucionReportar", "estadoAveria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAverias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAveriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAverias);

        btnEliminarAverias.setBackground(new java.awt.Color(35, 61, 83));
        btnEliminarAverias.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEliminarAverias.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarAverias.setText("ELIMINAR");
        btnEliminarAverias.setToolTipText("Elimina una mascota de la tabla");

        btnRefrescarAveria.setBackground(new java.awt.Color(6, 75, 115));
        btnRefrescarAveria.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnRefrescarAveria.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescarAveria.setText("REFRESCAR");
        btnRefrescarAveria.setToolTipText("Limpia los campos de la tabla");

        javax.swing.GroupLayout panelDetalleAveriasLayout = new javax.swing.GroupLayout(panelDetalleAverias);
        panelDetalleAverias.setLayout(panelDetalleAveriasLayout);
        panelDetalleAveriasLayout.setHorizontalGroup(
            panelDetalleAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleAveriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(panelDetalleAveriasLayout.createSequentialGroup()
                        .addComponent(lblBuscarAveria)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarAveria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarAveria))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleAveriasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefrescarAveria, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarAverias, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDetalleAveriasLayout.setVerticalGroup(
            panelDetalleAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleAveriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarAveria)
                    .addComponent(btnBuscarAveria)
                    .addComponent(txtBuscarAveria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelDetalleAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefrescarAveria)
                    .addComponent(btnEliminarAverias))
                .addContainerGap())
        );

        panelIngresarDatosMasc.setBackground(new java.awt.Color(255, 255, 255));
        panelIngresarDatosMasc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N
        panelIngresarDatosMasc.setToolTipText("Formulario para añadir una mascota");

        lblIdMasc.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblIdMasc.setText("Número de avería:");

        lblNombreMasc.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblNombreMasc.setText("Usuario:");

        lblNivelIncidencia.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblNivelIncidencia.setText("Nivel de Incidencia:");

        txtNumeroAveria.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        txtUsuario.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        lblProvincia.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblProvincia.setText("Provincia:");

        lblCanton.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblCanton.setText("Cantón:");

        btnCancelarAverias.setBackground(new java.awt.Color(153, 0, 0));
        btnCancelarAverias.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnCancelarAverias.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarAverias.setText("CANCELAR");
        btnCancelarAverias.setToolTipText("Cancela las acciones");

        btnGuardarAverias.setBackground(new java.awt.Color(255, 153, 0));
        btnGuardarAverias.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnGuardarAverias.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarAverias.setText("GUARDAR");
        btnGuardarAverias.setToolTipText("Guarda los cambios");

        btnEditarAverias.setBackground(new java.awt.Color(254, 189, 105));
        btnEditarAverias.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEditarAverias.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarAverias.setText("EDITAR");
        btnEditarAverias.setToolTipText("Actualiza la información de la mascota");

        cboxNivelIncidencia.setBackground(new java.awt.Color(102, 102, 102));
        cboxNivelIncidencia.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cboxNivelIncidencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Moderada", "Alta", "Muy Alta", "Extremadamente Alta" }));

        cboxProvincia.setBackground(new java.awt.Color(102, 102, 102));
        cboxProvincia.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cboxProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San José", "Heredia", "Cartago", "Limón", "Alajuela", "Guanacaste", "Puntarenas" }));

        lblActivoMasc.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblActivoMasc.setText("Estado de avería:");

        cboxEstadoAveria.setBackground(new java.awt.Color(102, 102, 102));
        cboxEstadoAveria.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cboxEstadoAveria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activa", "Trabajando", "Resuelta" }));

        lblDistrito.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblDistrito.setText("Distrito:");

        lblDireccion.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblDireccion.setText("Dirección:");

        txtDireccion.setColumns(20);
        txtDireccion.setRows(5);
        jScrollPane2.setViewportView(txtDireccion);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel1.setText("Descripción:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane3.setViewportView(txtDescripcion);

        lblImagen.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblImagen.setText("Imágen:");

        btnBuscarImagen.setBackground(new java.awt.Color(35, 61, 83));
        btnBuscarImagen.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnBuscarImagen.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarImagen.setText("BUSCAR IMÁGEN");
        btnBuscarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarImagenActionPerformed(evt);
            }
        });

        lblInstitucion.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblInstitucion.setText("Institución:");

        txtDistrito.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistritoActionPerformed(evt);
            }
        });

        txtCanton.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtCanton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantonActionPerformed(evt);
            }
        });

        txtFecha.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        lblFecha.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblFecha.setText("Fecha de averia:");

        JLImg.setBackground(new java.awt.Color(102, 102, 102));
        JLImg.setForeground(new java.awt.Color(153, 153, 153));
        JLImg.setText("Aqui ira la imagen");

        javax.swing.GroupLayout panelIngresarDatosMascLayout = new javax.swing.GroupLayout(panelIngresarDatosMasc);
        panelIngresarDatosMasc.setLayout(panelIngresarDatosMascLayout);
        panelIngresarDatosMascLayout.setHorizontalGroup(
            panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdMasc)
                            .addComponent(lblNombreMasc))
                        .addGap(16, 16, 16)
                        .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario)
                            .addComponent(txtNumeroAveria)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresarDatosMascLayout.createSequentialGroup()
                        .addComponent(btnEditarAverias, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(btnGuardarAverias, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarAverias, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresarDatosMascLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresarDatosMascLayout.createSequentialGroup()
                                .addComponent(lblProvincia)
                                .addGap(57, 57, 57))
                            .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                                .addComponent(lblCanton)
                                .addGap(67, 67, 67)))
                        .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxProvincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCanton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDistrito)
                            .addComponent(lblDireccion)
                            .addComponent(lblActivoMasc)
                            .addComponent(lblInstitucion))
                        .addGap(20, 20, 20)
                        .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxEstadoAveria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtInstitucion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(txtDistrito)))
                    .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNivelIncidencia)
                            .addComponent(lblFecha))
                        .addGap(12, 12, 12)
                        .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha)
                            .addComponent(cboxNivelIncidencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagen)
                            .addComponent(jLabel1))
                        .addGap(43, 43, 43)
                        .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                                .addComponent(btnBuscarImagen)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3)
                            .addComponent(JLImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelIngresarDatosMascLayout.setVerticalGroup(
            panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblIdMasc)
                    .addComponent(txtNumeroAveria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNombreMasc)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNivelIncidencia)
                    .addComponent(cboxNivelIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblFecha)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblProvincia)
                    .addComponent(cboxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCanton)
                    .addComponent(txtCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblDistrito)
                    .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblDireccion)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresarDatosMascLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)))
                .addGap(16, 16, 16)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblImagen)
                    .addComponent(btnBuscarImagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLImg, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInstitucion))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActivoMasc)
                    .addComponent(cboxEstadoAveria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarAverias)
                    .addComponent(btnEditarAverias)
                    .addComponent(btnCancelarAverias))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMantLayout = new javax.swing.GroupLayout(panelMant);
        panelMant.setLayout(panelMantLayout);
        panelMantLayout.setHorizontalGroup(
            panelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogoMasc)
                .addGap(224, 224, 224))
            .addGroup(panelMantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMantLayout.createSequentialGroup()
                        .addComponent(lblTitleAverias)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelMantLayout.createSequentialGroup()
                        .addComponent(panelIngresarDatosMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelDetalleAverias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelMantLayout.setVerticalGroup(
            panelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMantLayout.createSequentialGroup()
                .addGroup(panelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMantLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitleAverias))
                    .addGroup(panelMantLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogoMasc)
                        .addGap(61, 61, 61)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelIngresarDatosMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDetalleAverias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableAveriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAveriasMouseClicked
        try{

            int fila = tableAverias.getSelectedRow();
            txtNumeroAveria.setText(tableAverias.getValueAt(fila, 0).toString());
            txtUsuario.setText(tableAverias.getValueAt(fila, 1).toString());
            cboxNivelIncidencia.setSelectedItem(tableAverias.getValueAt(fila, 2));
            txtFecha.setText(tableAverias.getValueAt(fila, 3).toString());
            cboxProvincia.setSelectedItem(tableAverias.getValueAt(fila, 4));
            txtCanton.setText(tableAverias.getValueAt(fila, 5).toString());
            txtDistrito.setText(tableAverias.getValueAt(fila, 6).toString());
            txtDireccion.setText(tableAverias.getValueAt(fila, 7).toString());
            txtDescripcion.setText(tableAverias.getValueAt(fila, 8).toString());
            txtInstitucion.setText(tableAverias.getValueAt(fila, 9).toString());
            cboxEstadoAveria.setSelectedItem(tableAverias.getValueAt(fila, 10));

        }catch (Exception e){

            JOptionPane.showMessageDialog(this, "ERROR AL SELECCIONAR UN REGISTRO:" + e.getMessage());

        }

    }//GEN-LAST:event_tableAveriasMouseClicked

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnBuscarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarImagenActionPerformed
        File imagen;
        
        int resultado;

        frmBuscarImagen Buscador = new frmBuscarImagen();

        FileNameExtensionFilter formato = new FileNameExtensionFilter("JPG, PNG y GIF", "jpg", "png", "gif");

        Buscador.jFileChooser.setFileFilter(formato);

        resultado = Buscador.jFileChooser.showOpenDialog(null);

        if (JFileChooser.APPROVE_OPTION == resultado){

            imagen = Buscador.jFileChooser.getSelectedFile();

            try {
                ImageIcon ImgIcon = new ImageIcon(imagen.toString());

                Icon icono = new ImageIcon(ImgIcon.getImage().getScaledInstance(JLImg.getWidth(), JLImg.getHeight(), Image.SCALE_DEFAULT));

                JLImg.setIcon(icono);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al abrir: " + ex);
            }

        }

    }//GEN-LAST:event_btnBuscarImagenActionPerformed

    private void txtDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistritoActionPerformed

    private void txtCantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantonActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteyListadoAverias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteyListadoAverias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteyListadoAverias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteyListadoAverias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReporteyListadoAverias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLImg;
    public javax.swing.JButton btnBuscarAveria;
    public javax.swing.JButton btnBuscarImagen;
    public javax.swing.JButton btnCancelarAverias;
    public javax.swing.JButton btnEditarAverias;
    public javax.swing.JButton btnEliminarAverias;
    public javax.swing.JButton btnGuardarAverias;
    public javax.swing.JButton btnRefrescarAveria;
    public javax.swing.JComboBox<String> cboxEstadoAveria;
    public javax.swing.JComboBox<String> cboxNivelIncidencia;
    public javax.swing.JComboBox<String> cboxProvincia;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lblActivoMasc;
    public javax.swing.JLabel lblBuscarAveria;
    public javax.swing.JLabel lblCanton;
    public javax.swing.JLabel lblDireccion;
    public javax.swing.JLabel lblDistrito;
    public javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblIdMasc;
    public javax.swing.JLabel lblImagen;
    public javax.swing.JLabel lblInstitucion;
    public javax.swing.JLabel lblLogoMasc;
    public javax.swing.JLabel lblNivelIncidencia;
    public javax.swing.JLabel lblNombreMasc;
    public javax.swing.JLabel lblProvincia;
    public javax.swing.JLabel lblTitleAverias;
    public javax.swing.JPanel panelDetalleAverias;
    public javax.swing.JPanel panelIngresarDatosMasc;
    public javax.swing.JPanel panelMant;
    public javax.swing.JTable tableAverias;
    public javax.swing.JTextField txtBuscarAveria;
    public javax.swing.JTextField txtCanton;
    public javax.swing.JTextArea txtDescripcion;
    public javax.swing.JTextArea txtDireccion;
    public javax.swing.JTextField txtDistrito;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtInstitucion;
    public javax.swing.JTextField txtNumeroAveria;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
