/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelo.ReporteyListadoAveriasDAO;
import modelo.SeguimientoAveriasDAO;

/**
 *
 * @author Susana Burch
 */
public class frmSeguimientoAverias extends javax.swing.JFrame {

    
    String columnas[] = {"numeroAveria", "numeroSeguimiento", "descripcionSolucionAveria", "horasInvertidas", "cantidadEmpleadosInvolucrados", "costoAproximado", "nombrePersonaValidaArreglo", "imagenFinalizazacion"};
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
    SeguimientoAveriasDAO dao = new SeguimientoAveriasDAO();
    ArrayList<Object[]> registros = new ArrayList<>();

    private JFrame frame;
    /**
     * Creates new form frmSeguimientoAveria
     */
    public frmSeguimientoAverias() {
        initComponents();
        cargarTabla();
        this.setExtendedState(MAXIMIZED_BOTH);

    }
public frmSeguimientoAverias(JFrame frame) {
        initComponents();
        this.frame = frame;
        cargarTabla();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
     private void cargarTabla (){
         
        this.registros = dao.listar();
        modelo.setNumRows(0);
        for  (Object [] record : registros){
            this.modelo.addRow(record);
        }
        this.tblSeguimientoAverias.setModel(modelo);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMantenimientoAverias = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelDetalleSeguim = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeguimientoAverias = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        cboCriterioBusqueda = new javax.swing.JComboBox<>();
        lblLogoMasc = new javax.swing.JLabel();
        lblLogoMascota = new javax.swing.JLabel();
        panelReporteAverias = new javax.swing.JPanel();
        lblnumeroAveria = new javax.swing.JLabel();
        lblNivelIncidencia = new javax.swing.JLabel();
        txtnumeroAveria = new javax.swing.JTextField();
        lblCanton = new javax.swing.JLabel();
        btnCancelarAveria = new javax.swing.JButton();
        btnGuardarAveria = new javax.swing.JButton();
        btnEditarAveria = new javax.swing.JButton();
        lblDistrito = new javax.swing.JLabel();
        lblDireccionAveria = new javax.swing.JLabel();
        txtCantEmpleados = new javax.swing.JTextField();
        txtCostoAprox = new javax.swing.JTextField();
        lblDescripcionAveria = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcionAveria = new javax.swing.JTextArea();
        lblImagenAveria = new javax.swing.JLabel();
        lblEstadoAveria = new javax.swing.JLabel();
        cboxEstadoAveria = new javax.swing.JComboBox<>();
        btnBuscarImagenAveria = new javax.swing.JButton();
        txtHorasInvertidas = new javax.swing.JTextField();
        txtValidado = new javax.swing.JTextField();
        JLImg = new javax.swing.JLabel();
        lblnumeroAveria1 = new javax.swing.JLabel();
        txtnumeroSegAveria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMantenimientoAverias.setBackground(new java.awt.Color(255, 255, 255));
        panelMantenimientoAverias.setForeground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        lblTitulo.setText("SEGUIMIENTO DE AVERÍAS");
        lblTitulo.setBorder(new javax.swing.border.MatteBorder(null));

        panelDetalleSeguim.setBackground(new java.awt.Color(255, 255, 255));
        panelDetalleSeguim.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(35, 47, 62));
        btnBuscar.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setToolTipText("");

        txtBuscar.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        tblSeguimientoAverias.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        tblSeguimientoAverias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "numeroAveria", "numeroSeguimiento", "descripcionSolucionAveria", "horasInvertidas", "cantidadEmpleadosInvolucrados", "costoAproximado", "nombrePersonaValidaArreglo", "imagenFinalizacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSeguimientoAverias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeguimientoAveriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSeguimientoAverias);

        btnSalir.setBackground(new java.awt.Color(102, 0, 0));
        btnSalir.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.setToolTipText("Eliminar una avería de la tabla");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnRefrescar.setBackground(new java.awt.Color(204, 204, 204));
        btnRefrescar.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnRefrescar.setText("REFRESCAR");
        btnRefrescar.setToolTipText("Limpia los campos de la tabla");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        cboCriterioBusqueda.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cboCriterioBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Provincia", "Canton", "Distrito", "FechaIngreso", "NivelIncidencia", "Institucion" }));

        javax.swing.GroupLayout panelDetalleSeguimLayout = new javax.swing.GroupLayout(panelDetalleSeguim);
        panelDetalleSeguim.setLayout(panelDetalleSeguimLayout);
        panelDetalleSeguimLayout.setHorizontalGroup(
            panelDetalleSeguimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleSeguimLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleSeguimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelDetalleSeguimLayout.createSequentialGroup()
                        .addComponent(cboCriterioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleSeguimLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDetalleSeguimLayout.setVerticalGroup(
            panelDetalleSeguimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleSeguimLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleSeguimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboCriterioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(panelDetalleSeguimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefrescar)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        panelDetalleSeguimLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBuscar, cboCriterioBusqueda, txtBuscar});

        panelReporteAverias.setBackground(new java.awt.Color(255, 255, 255));
        panelReporteAverias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N
        panelReporteAverias.setToolTipText("Formulario para reportar una avería");

        lblnumeroAveria.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblnumeroAveria.setText("Numero de averia:");

        lblNivelIncidencia.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblNivelIncidencia.setText("Cantidad Horas Invertidas:");

        txtnumeroAveria.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        lblCanton.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblCanton.setText("Cantidad Empleados Involucrados:");

        btnCancelarAveria.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelarAveria.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnCancelarAveria.setText("CANCELAR");
        btnCancelarAveria.setToolTipText("Cancela las acciones");

        btnGuardarAveria.setBackground(new java.awt.Color(35, 47, 62));
        btnGuardarAveria.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnGuardarAveria.setText("GUARDAR");
        btnGuardarAveria.setToolTipText("Guarda los cambios");

        btnEditarAveria.setBackground(new java.awt.Color(204, 204, 204));
        btnEditarAveria.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEditarAveria.setText("EDITAR");
        btnEditarAveria.setToolTipText("Edita la avería de la tabla");
        btnEditarAveria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAveriaActionPerformed(evt);
            }
        });

        lblDistrito.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblDistrito.setText("Costo aproximado");

        lblDireccionAveria.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblDireccionAveria.setText("Validado por:");

        txtCantEmpleados.setAutoscrolls(false);
        txtCantEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantEmpleadosActionPerformed(evt);
            }
        });

        txtCostoAprox.setAutoscrolls(false);

        lblDescripcionAveria.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblDescripcionAveria.setText("Descripción Solucion:");

        txtDescripcionAveria.setColumns(20);
        txtDescripcionAveria.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtDescripcionAveria.setRows(5);
        jScrollPane3.setViewportView(txtDescripcionAveria);

        lblImagenAveria.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblImagenAveria.setText("Imágen:");

        lblEstadoAveria.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblEstadoAveria.setText("Estado de avería:");

        cboxEstadoAveria.setBackground(new java.awt.Color(102, 102, 102));
        cboxEstadoAveria.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cboxEstadoAveria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pausa", "Finalizado" }));

        btnBuscarImagenAveria.setBackground(new java.awt.Color(35, 47, 62));
        btnBuscarImagenAveria.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnBuscarImagenAveria.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarImagenAveria.setText("BUSCAR IMAGEN");
        btnBuscarImagenAveria.setToolTipText("Busca por nombre la mascota");
        btnBuscarImagenAveria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarImagenAveriaActionPerformed(evt);
            }
        });

        txtHorasInvertidas.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        txtValidado.setAutoscrolls(false);

        JLImg.setBackground(new java.awt.Color(102, 102, 102));
        JLImg.setForeground(new java.awt.Color(153, 153, 153));
        JLImg.setText("Aqui ira la imagen");

        lblnumeroAveria1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblnumeroAveria1.setText("Numero Seguimiento de averia:");

        txtnumeroSegAveria.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtnumeroSegAveria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroSegAveriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReporteAveriasLayout = new javax.swing.GroupLayout(panelReporteAverias);
        panelReporteAverias.setLayout(panelReporteAveriasLayout);
        panelReporteAveriasLayout.setHorizontalGroup(
            panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteAveriasLayout.createSequentialGroup()
                .addGroup(panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReporteAveriasLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstadoAveria)
                            .addGroup(panelReporteAveriasLayout.createSequentialGroup()
                                .addComponent(btnGuardarAveria, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnEditarAveria, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnCancelarAveria, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelReporteAveriasLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblnumeroAveria1))
                    .addGroup(panelReporteAveriasLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblImagenAveria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelReporteAveriasLayout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(cboxEstadoAveria, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelReporteAveriasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnumeroAveria)
                            .addComponent(lblNivelIncidencia)
                            .addComponent(lblCanton)
                            .addComponent(lblDescripcionAveria)
                            .addComponent(lblDistrito)
                            .addComponent(lblDireccionAveria))
                        .addGap(18, 18, 18)
                        .addGroup(panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCostoAprox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantEmpleados, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHorasInvertidas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnumeroSegAveria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarImagenAveria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLImg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnumeroAveria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValidado)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panelReporteAveriasLayout.setVerticalGroup(
            panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteAveriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnumeroAveria)
                    .addComponent(txtnumeroAveria))
                .addGap(18, 18, 18)
                .addGroup(panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnumeroAveria1)
                    .addComponent(txtnumeroSegAveria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNivelIncidencia)
                    .addComponent(txtHorasInvertidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCanton)
                    .addComponent(txtCantEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDistrito)
                    .addComponent(txtCostoAprox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccionAveria)
                    .addComponent(txtValidado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcionAveria)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagenAveria)
                    .addComponent(btnBuscarImagenAveria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLImg, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxEstadoAveria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoAveria))
                .addGap(18, 18, 18)
                .addGroup(panelReporteAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarAveria)
                    .addComponent(btnEditarAveria)
                    .addComponent(btnCancelarAveria))
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout panelMantenimientoAveriasLayout = new javax.swing.GroupLayout(panelMantenimientoAverias);
        panelMantenimientoAverias.setLayout(panelMantenimientoAveriasLayout);
        panelMantenimientoAveriasLayout.setHorizontalGroup(
            panelMantenimientoAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantenimientoAveriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMantenimientoAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMantenimientoAveriasLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 528, Short.MAX_VALUE)
                        .addGroup(panelMantenimientoAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMantenimientoAveriasLayout.createSequentialGroup()
                                .addComponent(lblLogoMasc)
                                .addGap(224, 224, 224))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMantenimientoAveriasLayout.createSequentialGroup()
                                .addComponent(lblLogoMascota)
                                .addGap(230, 230, 230))))
                    .addGroup(panelMantenimientoAveriasLayout.createSequentialGroup()
                        .addComponent(panelReporteAverias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelDetalleSeguim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelMantenimientoAveriasLayout.setVerticalGroup(
            panelMantenimientoAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantenimientoAveriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogoMasc)
                .addGap(12, 12, 12)
                .addGroup(panelMantenimientoAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(lblLogoMascota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMantenimientoAveriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelReporteAverias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDetalleSeguim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMantenimientoAverias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMantenimientoAverias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSeguimientoAveriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeguimientoAveriasMouseClicked

    }//GEN-LAST:event_tblSeguimientoAveriasMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
         this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void txtCantEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantEmpleadosActionPerformed
  File imagen; // tal vez error

    private void btnBuscarImagenAveriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarImagenAveriaActionPerformed

       int resultado;
       
       frmBuscarImagen Buscador = new frmBuscarImagen();

       FileNameExtensionFilter formato = new FileNameExtensionFilter("JPG, PNG y GIF", "jpg", "png", "gif");
       
       Buscador.jFileChooser.setFileFilter(formato);
       
       resultado = Buscador.jFileChooser.showOpenDialog(null);
       
       if (JFileChooser.APPROVE_OPTION == resultado){
           
           imagen = Buscador.jFileChooser.getSelectedFile();
           
           try {
               ImageIcon ImgIcon = new ImageIcon(imagen.toString());
               
               Icon icono = new ImageIcon(ImgIcon.getImage().getScaledInstance(JLImg.getWidth(), JLImg.getHeight(), Image.SCALE_DEFAULT));
               
               JLImg.setIcon(icono);
               
           } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "Error al abrir: " + ex);
           }
           
       }
        
        
        
        
        
    }//GEN-LAST:event_btnBuscarImagenAveriaActionPerformed

    private void btnEditarAveriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAveriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarAveriaActionPerformed

    private void txtnumeroSegAveriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroSegAveriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroSegAveriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSeguimientoAverias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSeguimientoAverias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSeguimientoAverias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSeguimientoAverias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSeguimientoAverias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLImg;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnBuscarImagenAveria;
    public javax.swing.JButton btnCancelarAveria;
    public javax.swing.JButton btnEditarAveria;
    public javax.swing.JButton btnGuardarAveria;
    public javax.swing.JButton btnRefrescar;
    public javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboCriterioBusqueda;
    public javax.swing.JComboBox<String> cboxEstadoAveria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lblCanton;
    public javax.swing.JLabel lblDescripcionAveria;
    public javax.swing.JLabel lblDireccionAveria;
    public javax.swing.JLabel lblDistrito;
    private javax.swing.JLabel lblEstadoAveria;
    public javax.swing.JLabel lblImagenAveria;
    public javax.swing.JLabel lblLogoMasc;
    private javax.swing.JLabel lblLogoMascota;
    public javax.swing.JLabel lblNivelIncidencia;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JLabel lblnumeroAveria;
    public javax.swing.JLabel lblnumeroAveria1;
    public javax.swing.JPanel panelDetalleSeguim;
    public javax.swing.JPanel panelMantenimientoAverias;
    public javax.swing.JPanel panelReporteAverias;
    public javax.swing.JTable tblSeguimientoAverias;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtCantEmpleados;
    public javax.swing.JTextField txtCostoAprox;
    public javax.swing.JTextArea txtDescripcionAveria;
    public javax.swing.JTextField txtHorasInvertidas;
    public javax.swing.JTextField txtValidado;
    public javax.swing.JTextField txtnumeroAveria;
    public javax.swing.JTextField txtnumeroSegAveria;
    // End of variables declaration//GEN-END:variables
}
