/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControllerUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author two_r
 */
public class frmUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmUsuario
     */
    public frmUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMantMasc = new javax.swing.JPanel();
        lblTitleClientes = new javax.swing.JLabel();
        panelDetalleUser = new javax.swing.JPanel();
        lblBuscarNombreUser = new javax.swing.JLabel();
        btnBuscarUser = new javax.swing.JButton();
        txtBuscarNombreUser = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        btnEliminarUser = new javax.swing.JButton();
        btnRefrescarUser = new javax.swing.JButton();
        panelIngresarDatosUser = new javax.swing.JPanel();
        lblIdUserFrm = new javax.swing.JLabel();
        lblNombreUser = new javax.swing.JLabel();
        lbl1ApellidoUser = new javax.swing.JLabel();
        txtIdUserFrm = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        btnCancelarUser = new javax.swing.JButton();
        btnGuardarUser = new javax.swing.JButton();
        btnEditarUser = new javax.swing.JButton();
        lblNombreCompleto = new javax.swing.JLabel();
        cboxTipoUserFrm = new javax.swing.JComboBox<>();
        lblTipoUserFrm = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        lblhabilitado = new javax.swing.JLabel();
        chkbxHabilitado = new javax.swing.JCheckBox();
        txtContrasenaUser = new javax.swing.JTextField();
        lblLogoUser = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ventana Usuarios");

        panelMantMasc.setBackground(new java.awt.Color(255, 255, 255));
        panelMantMasc.setForeground(new java.awt.Color(255, 255, 255));

        lblTitleClientes.setFont(new java.awt.Font("SansSerif", 3, 22)); // NOI18N
        lblTitleClientes.setText("MANTENIMIENTO DE USUARIOS");

        panelDetalleUser.setBackground(new java.awt.Color(255, 255, 255));
        panelDetalleUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        lblBuscarNombreUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblBuscarNombreUser.setText("Buscar por Nombre:");

        btnBuscarUser.setBackground(new java.awt.Color(255, 153, 0));
        btnBuscarUser.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnBuscarUser.setText("BUSCAR");
        btnBuscarUser.setToolTipText("Buscar por nombre el usuario");

        txtBuscarNombreUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtBuscarNombreUser.setToolTipText("Ingrese un nombre para buscar y filtrar la tabla");

        tableUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "usuario", "cedula", "conrasena", "nombreCompleto", "tipoRol", "habilitado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableUser);
        if (tableUser.getColumnModel().getColumnCount() > 0) {
            tableUser.getColumnModel().getColumn(0).setResizable(false);
            tableUser.getColumnModel().getColumn(1).setResizable(false);
            tableUser.getColumnModel().getColumn(2).setResizable(false);
            tableUser.getColumnModel().getColumn(3).setResizable(false);
            tableUser.getColumnModel().getColumn(4).setResizable(false);
        }

        btnEliminarUser.setBackground(new java.awt.Color(35, 61, 83));
        btnEliminarUser.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEliminarUser.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarUser.setText("ELIMINAR");
        btnEliminarUser.setToolTipText("Elimina un usuario de la tabla");

        btnRefrescarUser.setBackground(new java.awt.Color(6, 75, 115));
        btnRefrescarUser.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnRefrescarUser.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescarUser.setText("REFRESCAR");
        btnRefrescarUser.setToolTipText("Refresca los usuarios de la tabla");

        javax.swing.GroupLayout panelDetalleUserLayout = new javax.swing.GroupLayout(panelDetalleUser);
        panelDetalleUser.setLayout(panelDetalleUserLayout);
        panelDetalleUserLayout.setHorizontalGroup(
            panelDetalleUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addGroup(panelDetalleUserLayout.createSequentialGroup()
                        .addComponent(lblBuscarNombreUser)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarNombreUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarUser))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleUserLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefrescarUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarUser)))
                .addContainerGap())
        );
        panelDetalleUserLayout.setVerticalGroup(
            panelDetalleUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarNombreUser)
                    .addComponent(btnBuscarUser)
                    .addComponent(txtBuscarNombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetalleUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefrescarUser)
                    .addComponent(btnEliminarUser))
                .addContainerGap())
        );

        panelIngresarDatosUser.setBackground(new java.awt.Color(255, 255, 255));
        panelIngresarDatosUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        lblIdUserFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblIdUserFrm.setText("ID de Usuario:");

        lblNombreUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblNombreUser.setText("Cedula:");

        lbl1ApellidoUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lbl1ApellidoUser.setText("Contraseña:");

        txtIdUserFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        txtCedula.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        btnCancelarUser.setBackground(new java.awt.Color(35, 61, 83));
        btnCancelarUser.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnCancelarUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarUser.setText("CANCELAR");
        btnCancelarUser.setToolTipText("Cancelan todas las acciones");

        btnGuardarUser.setBackground(new java.awt.Color(255, 153, 0));
        btnGuardarUser.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnGuardarUser.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarUser.setText("GUARDAR");
        btnGuardarUser.setToolTipText("Guardar los cambios de usuario");

        btnEditarUser.setBackground(new java.awt.Color(254, 189, 105));
        btnEditarUser.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEditarUser.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarUser.setText("EDITAR");
        btnEditarUser.setToolTipText("Actualiza el usuario existente");

        lblNombreCompleto.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblNombreCompleto.setText("Nombre Completo:");

        cboxTipoUserFrm.setBackground(new java.awt.Color(102, 102, 102));
        cboxTipoUserFrm.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cboxTipoUserFrm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Asistente", "Invitado" }));

        lblTipoUserFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblTipoUserFrm.setText("Tipo de Rol:");

        txtNombreCompleto.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtNombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCompletoActionPerformed(evt);
            }
        });

        lblhabilitado.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblhabilitado.setText("Habilitado");

        chkbxHabilitado.setBackground(new java.awt.Color(255, 255, 255));
        chkbxHabilitado.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        txtContrasenaUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtContrasenaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIngresarDatosUserLayout = new javax.swing.GroupLayout(panelIngresarDatosUser);
        panelIngresarDatosUser.setLayout(panelIngresarDatosUserLayout);
        panelIngresarDatosUserLayout.setHorizontalGroup(
            panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosUserLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnGuardarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(panelIngresarDatosUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdUserFrm)
                    .addComponent(lblNombreUser)
                    .addComponent(lbl1ApellidoUser)
                    .addComponent(lblNombreCompleto)
                    .addComponent(lblTipoUserFrm)
                    .addComponent(lblhabilitado))
                .addGap(39, 39, 39)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdUserFrm, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(txtContrasenaUser)
                    .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(cboxTipoUserFrm, 0, 218, Short.MAX_VALUE)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(chkbxHabilitado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelIngresarDatosUserLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboxTipoUserFrm, txtCedula, txtIdUserFrm, txtNombreCompleto});

        panelIngresarDatosUserLayout.setVerticalGroup(
            panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdUserFrm)
                    .addComponent(txtIdUserFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreUser)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1ApellidoUser)
                    .addComponent(txtContrasenaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCompleto)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoUserFrm)
                    .addComponent(cboxTipoUserFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblhabilitado)
                    .addComponent(chkbxHabilitado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarUser)
                    .addComponent(btnEditarUser)
                    .addComponent(btnCancelarUser))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMantMascLayout = new javax.swing.GroupLayout(panelMantMasc);
        panelMantMasc.setLayout(panelMantMascLayout);
        panelMantMascLayout.setHorizontalGroup(
            panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantMascLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMantMascLayout.createSequentialGroup()
                        .addComponent(lblTitleClientes)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelIngresarDatosUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMantMascLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(lblLogoUser))
                    .addGroup(panelMantMascLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDetalleUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelMantMascLayout.setVerticalGroup(
            panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantMascLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleClientes)
                    .addGroup(panelMantMascLayout.createSequentialGroup()
                        .addComponent(lblLogoUser)
                        .addGap(35, 35, 35)
                        .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelDetalleUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelIngresarDatosUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMantMasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelMantMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUserMouseClicked
      try{
        
            int fila = tableUser.getSelectedRow();
            txtIdUserFrm.setText(tableUser.getValueAt(fila, 0).toString());
            txtCedula.setText(tableUser.getValueAt(fila, 1).toString());
            txtContrasenaUser.setText(tableUser.getValueAt(fila, 2).toString());
            txtNombreCompleto.setText(tableUser.getValueAt(fila, 3).toString());
            cboxTipoUserFrm.setSelectedItem(tableUser.getValueAt(fila, 4));
            
            
        }catch (Exception e){
        
            JOptionPane.showMessageDialog(this, "ERROR AL SELECCIONAR UN REGISTRO:" + e.getMessage());
            
        }       
    }//GEN-LAST:event_tableUserMouseClicked

    private void txtNombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCompletoActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtContrasenaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                frmUsuario user = new frmUsuario();
                ControllerUsuario con = new ControllerUsuario(user);
                con.iniciar();
                user.setVisible(true);
                user.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarUser;
    public javax.swing.JButton btnCancelarUser;
    public javax.swing.JButton btnEditarUser;
    public javax.swing.JButton btnEliminarUser;
    public javax.swing.JButton btnGuardarUser;
    public javax.swing.JButton btnRefrescarUser;
    public javax.swing.JComboBox<String> cboxTipoUserFrm;
    public javax.swing.JCheckBox chkbxHabilitado;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbl1ApellidoUser;
    public javax.swing.JLabel lblBuscarNombreUser;
    public javax.swing.JLabel lblIdUserFrm;
    public javax.swing.JLabel lblLogoUser;
    public javax.swing.JLabel lblNombreCompleto;
    public javax.swing.JLabel lblNombreUser;
    public javax.swing.JLabel lblTipoUserFrm;
    public javax.swing.JLabel lblTitleClientes;
    private javax.swing.JLabel lblhabilitado;
    public javax.swing.JPanel panelDetalleUser;
    public javax.swing.JPanel panelIngresarDatosUser;
    public javax.swing.JPanel panelMantMasc;
    public javax.swing.JTable tableUser;
    public javax.swing.JTextField txtBuscarNombreUser;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtContrasenaUser;
    public javax.swing.JTextField txtIdUserFrm;
    public javax.swing.JTextField txtNombreCompleto;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
